eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: say-hello-service
spring.zipkin.base-url: http://localhost:9411